name: Update redmine 1
on: [push, pull_request]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run the upgrade script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo sh /home/ubuntu/redmine.sh
          host: ${{ secrets.HOST1 }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATE_KEY1}}
        env:
          CI: true
          
          
