name: Update redmine 2
on: [push, pull_request, workflow_dispatch]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run the upgrade script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo sh /home/ubuntu/redmine.sh
          host: ${{ secrets.HOST2 }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATE_KEY2}}
        env:
          CI: true
          
          
