
name: Upgrade to new version
on: 
  workflow_dispatch: 
  workflow_run: 
jobs:
  aboba:
    runs-on: ubuntu-latest
    steps:
      - name: Run the upgrade script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo bash /home/ubuntu/example-voting-app/upgrade.sh
          host: ${{ secrets.HOST }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
